version: '3'
services:
  db:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=Odoo@16custom
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    depends_on:
#      - db
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - /tmp/pgadmin:/var/lib/pgadmin
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
##    networks:
##      - postgres
#    restart: unless-stopped

  odoo16:
    image: odoo:16
    user: root
    depends_on:
      - db
    ports:
      - "10016:8069"
      - "20016:8072" # live chat
    tty: true
    # command: mkdir /usr/lib/python3/dist-packages/odoo/addons/odoo_restapi
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=Odoo@16custom
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons/rest-api:/usr/lib/python3/dist-packages/odoo/addons/odoo_restapi
      - ./etc:/etc/odoo
    restart: always             # run as a service

  nginx:
    depends_on:
      - odoo16
    container_name: odoo_proxy
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8888:8069"
    